services:
  - name: prolific-ghl-webhook
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/montelli99/prolific-ghl-webhook
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_k2RUfn9gacAe@ep-wandering-thunder-ahesitw4-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production