#!/usr/bin/env node
'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { buildSyncAwarePreview, classifyGhlCallSync, persistSyncAwarePreview } = require('./ghl-call-sync-classifier');
const { TranscriptNoteApprovalStore, TranscriptNotePreviewStore } = require('./owner-controlled-transcript-note');

const statuses = { contact: 200, notes: 200, conversations: 200, tasks: 200, opportunities: 200 };
const task = { id: 'task-1', title: 'Outgoing call', body: 'Call ID: 400683713\nCall Duration: 00h 00m 32s\nCall Recording: https://masked.invalid/r', dueDate: '2026-08-04T13:59:48Z', completed: true };
const preview = { previewId: 'old-preview', previewHash: 'old-hash', callId: '400683713', transcriptHash: 'provider-hash', testContactId: 'PSVc2FuuA0dqyaQPXqOE', normalizedTranscript: 'Exact normalized transcript.', transcriptMetadata: { retrievedAt: '2026-08-04T16:00:00Z' }, structuredFacts: { facts: [] }, riskFlags: [], productionEffects: {} };
let passed = 0;
let failed = 0;
async function test(name, fn) { try { await fn(); passed++; console.log(`PASS ${name}`); } catch (error) { failed++; console.error(`FAIL ${name}: ${error.message}`); } }

(async () => {
  await test('1 call activity is distinguishable from transcript text', () => { const result = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); assert.strictEqual(result.statuses.CALL_ACTIVITY, 'PRESENT'); assert.strictEqual(result.statuses.TRANSCRIPT_TEXT, 'ABSENT'); });
  await test('2 recording link is not transcript', () => { const result = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); assert.strictEqual(result.statuses.RECORDING_LINK, 'PRESENT'); assert.strictEqual(result.transcriptComparison, 'ABSENT'); });
  await test('3 transcript link is not transcript body', () => { const note = { body: 'Call ID: 400683713\nTranscript Link: https://masked.invalid/t' }; const result = classifyGhlCallSync({ callId: '400683713', notes: [note], endpointStatuses: statuses }); assert.strictEqual(result.statuses.TRANSCRIPT_LINK, 'PRESENT'); assert.strictEqual(result.statuses.TRANSCRIPT_TEXT, 'ABSENT'); });
  await test('4 summary is not transcript', () => { const note = { body: 'Call ID: 400683713\nCall Summary: Test summary only.' }; const result = classifyGhlCallSync({ callId: '400683713', notes: [note], endpointStatuses: statuses }); assert.strictEqual(result.statuses.CALL_SUMMARY, 'PRESENT'); assert.strictEqual(result.statuses.TRANSCRIPT_TEXT, 'ABSENT'); });
  await test('5 exact call ID or SID is required', () => { const result = classifyGhlCallSync({ callId: '400683713', tasks: [{ ...task, body: task.body.replace('400683713', '999') }], endpointStatuses: statuses }); assert.strictEqual(result.matchingRecords.length, 0); });
  await test('6 existing equivalent transcript blocks duplicate note', () => { const note = { body: 'Call ID: 400683713\nTranscript: Exact normalized transcript.' }; const result = classifyGhlCallSync({ callId: '400683713', notes: [note], endpointStatuses: statuses, providerTranscriptText: 'Exact normalized transcript.' }); assert.strictEqual(result.duplicationClassification, 'WRITE_NOT_NEEDED_TRANSCRIPT_ALREADY_PRESENT'); });
  await test('7 metadata-only activity permits reduced note', () => { const result = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); assert.strictEqual(result.duplicationClassification, 'WRITE_SHOULD_BE_REDUCED'); });
  await test('8 partial transcript produces warning classification', () => { const note = { body: 'Call ID: 400683713\nTranscript: Exact normalized' }; const result = classifyGhlCallSync({ callId: '400683713', notes: [note], endpointStatuses: statuses, providerTranscriptText: 'Exact normalized transcript.' }); assert.strictEqual(result.transcriptComparison, 'PARTIAL'); });
  await test('9 unknown GHL visibility blocks write', () => { const result = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: { ...statuses, conversations: 403 } }); assert.strictEqual(result.duplicationClassification, 'WRITE_BLOCKED_UNCERTAIN_EXISTING_DATA'); assert.strictEqual(result.statuses.TRANSCRIPT_TEXT, 'UNKNOWN'); });
  await test('10 revised preview requires its new exact approval language', () => { const sync = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); const revised = buildSyncAwarePreview({ ...preview, status: 'NOTE_PREVIEW_PENDING_APPROVAL', ownerId: 'owner', noteBodyHash: 'old-body' }, sync, sync.matchingRecords[0], new Date(Date.now())); assert.notStrictEqual(revised.previewId, preview.previewId); assert.notStrictEqual(revised.previewHash, preview.previewHash); assert.strictEqual(revised.approvalId, null); assert.match(revised.approvalInstruction, /revised/); const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-approval-')); const previewStore = new TranscriptNotePreviewStore({ dir: path.join(dir, 'previews') }); previewStore.persist(revised); const store = new TranscriptNoteApprovalStore({ dir: path.join(dir, 'approvals'), signingSecret: 'secret', ownerId: 'owner', previewStore, verifyOwnerContext: context => context.authenticated === true }); assert.throws(() => store.approve(revised, 'Approve the exact test note shown above.', { authenticated: true, ownerId: 'owner' }), /APPROVAL_LANGUAGE_REQUIRED/); assert.ok(store.approve(revised, revised.approvalInstruction, { authenticated: true, ownerId: 'owner' }).approvalId); fs.rmSync(dir, { recursive: true, force: true }); });
  await test('11 inspection performs no GHL write', () => assert.strictEqual(classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }).productionEffects.ghlWrites, 0));
  await test('12 inspection performs no stage movement', () => assert.strictEqual(classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }).productionEffects.stageMovements, 0));
  await test('13 inspection performs no SMS or automatic call', () => { const effects = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }).productionEffects; assert.strictEqual(effects.smsSent, 0); assert.strictEqual(effects.callsAutomaticallyPlaced, 0); });
  await test('14 final state remains PAUSED', () => assert.strictEqual(require('../bot/kill-switch').readKillSwitch().state, 'PAUSED'));
  await test('15 superseding a preview revokes its active approval and blocks stale approval', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-supersede-')); const previewStore = new TranscriptNotePreviewStore({ dir: path.join(dir, 'previews') }); const approvalStore = new TranscriptNoteApprovalStore({ dir: path.join(dir, 'approvals'), signingSecret: 'secret', ownerId: 'owner', previewStore, verifyOwnerContext: context => context.authenticated === true }); const active = { ...preview, status: 'NOTE_PREVIEW_PENDING_APPROVAL', ownerId: 'owner', noteBodyHash: 'old-body', approvalInstruction: 'Approve old.' }; previewStore.persist(active); const approval = approvalStore.approve(active, 'Approve old.', { authenticated: true, ownerId: 'owner' }); const sync = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); const revised = buildSyncAwarePreview(active, sync, sync.matchingRecords[0]); await persistSyncAwarePreview({ previewStore, approvalStore, existingPreviewId: active.previewId, revisedPreview: revised }); assert.match(previewStore.load(active.previewId).status, /SUPERSEDED/); assert.strictEqual(approvalStore.load(approval.approvalId).status, 'REVOKED'); assert.throws(() => approvalStore.approve(active, 'Approve old.', { authenticated: true, ownerId: 'owner' }), /PREVIEW_NOT_ACTIVE/); fs.rmSync(dir, { recursive: true, force: true }); });
  await test('16 empty transcript section cannot consume summary or link', () => { const summary = classifyGhlCallSync({ callId: '400683713', notes: [{ body: 'Call ID: 400683713\nTranscript:\nCall Summary: summary only' }], endpointStatuses: statuses, providerTranscriptText: 'summary only' }); const link = classifyGhlCallSync({ callId: '400683713', notes: [{ body: 'Call ID: 400683713\nTranscript:\nTranscript Link: https://masked.invalid/t' }], endpointStatuses: statuses, providerTranscriptText: 'https://masked.invalid/t' }); assert.strictEqual(summary.statuses.TRANSCRIPT_TEXT, 'ABSENT'); assert.strictEqual(link.statuses.TRANSCRIPT_TEXT, 'ABSENT'); });
  await test('17 conflicting call ID and SID are rejected', () => { const result = classifyGhlCallSync({ callId: '400683713', callSid: 'CAaaaaaaaaaaaaaaaaaaaa', tasks: [{ body: 'Call ID: 400683713\nCall SID: CAbbbbbbbbbbbbbbbbbbbb' }], endpointStatuses: statuses }); assert.strictEqual(result.matchingRecords.length, 0); });
  await test('18 revised preview strips raw task content and URLs', () => { const sync = classifyGhlCallSync({ callId: '400683713', tasks: [task], endpointStatuses: statuses }); const revised = buildSyncAwarePreview(preview, sync, { ...sync.matchingRecords[0], content: 'Call Recording: https://secret.invalid/token' }); assert.strictEqual('content' in revised.ghlAutoSync.record, false); assert.strictEqual(JSON.stringify(revised).includes('secret.invalid'), false); });
  await test('19 repeated identical call IDs still match existing note', () => { const note = { body: 'Call ID: 400683713\nTranscript: Exact normalized transcript.\nCall ID: 400683713' }; const result = classifyGhlCallSync({ callId: '400683713', notes: [note], endpointStatuses: statuses, providerTranscriptText: 'Exact normalized transcript.\nCall ID: 400683713' }); assert.strictEqual(result.matchingRecords.length, 1); });
  console.log(`\n${passed}/${passed + failed} tests passed`);
  if (failed) process.exit(1);
})().catch(error => { console.error(error); process.exit(1); });
